# Terminfo
set -g default-terminal "xterm-ghostty"
set -sa terminal-features ",xterm-ghostty:RGB"
# Don't wait after ESC pressed
set -sg escape-time 0
# Status bar refresh interval
set -g status-interval 1

# don't rename windows automatically
set -g allow-rename off

#set-window-option -g mode-keys vi
#set -g history-limit 5000

# Window index starting at 1
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-space
bind C-space send-prefix # press prefix twice to send the shortcut to the shell

# split panes using | and -
bind | split-window -hc "${pane_current_path}"
bind v split-window -hc "${pane_current_path}"
bind - split-window -vc "${pane_current_path}"
bind h split-window -vc "${pane_current_path}"
unbind '"'
unbind %

# switch panes using Alt-<arrow> and Alt-<vi-motion> without prefix
#bind -n M-h select-pane -L
#bind -n M-l select-pane -R
#bind -n M-k select-pane -U
#bind -n M-j select-pane -D
#bind -n M-Left select-pane -L
#bind -n M-Right select-pane -R
#bind -n M-Up select-pane -U
#bind -n M-Down select-pane -D

# Other custom shortcuts
bind c new-window -c '#{pane_current_path}' # 'prefix-c' new window on cwd
bind b break-pane -d # break current pane into a new window
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on
# Enable mouse control (clickable windows, panes, resizable panes)
#set -g mouse-select-window on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on

# Catppuccin theme
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_pane_status_enabled "yes" # set to "yes" to enable
set -g @catppuccin_window_text " #(smart_basename \"#{pane_current_path}\")"
set -g @catppuccin_window_current_text " #(smart_basename \"#{pane_current_path}\")"

# Kube context in status bar
# set -g @kubectx-format "%{context}/%{user}@%{cluster}:%{namespace}"
# set -g status-right '#[bg=blue]#{kubectx_context}:#[bg=red]#{kubectx_namespace}#[default]'

run "$HOME/.local/share/tpm/catppuccin/catppuccin.tmux"

set -g status-right ""
set -agF status-right "#{E:@catppuccin_status_kube}"
# TODO: add time + date on the right

set -g status-left ""
# atrocity to get the session name on the left
set -agF status-left \
	"#[fg=#{@catppuccin_session_color}]#{@catppuccin_status_left_separator}\
	#[fg=#{@catppuccin_status_session_icon_fg},bg=#{@catppuccin_status_session_icon_bg}]#{@catppuccin_session_icon}\
	#{@catppuccin_status_middle_separator}\
	#[fg=#{@thm_fg},bg=#{@catppuccin_status_module_text_bg}]\
	#{@catppuccin_session_text}\
	#[fg=#{@catppuccin_status_module_text_bg},bg=#{@thm_mantle}] \
	"

# TPM (tmux plugin manager)
# keep at bottom of file
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tpm"

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tony-sol/tmux-kubectx"

run "$HOME/.local/share/tmux/tpm/tpm"
